diff --git a/Dockerfile b/Dockerfile
index 550db90..aec72d6 100644
--- a/Dockerfile
+++ b/Dockerfile
@@ -1,41 +1,58 @@
-FROM ubuntu:22.04
+ARG BASE_IMAGE=zhangdafei1995/my_ollvm:latest
+FROM ${BASE_IMAGE}
 
-RUN apt-get update -qq && \
-    DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
-    git wget bzip2 file unzip libtool pkg-config cmake build-essential \
-    automake yasm gettext autopoint vim-tiny python3 python3-distutils \
-    ninja-build ca-certificates curl less zip && \
-    apt-get clean -y && \
-    rm -rf /var/lib/apt/lists/*
+ARG REBUILD_FROM_SOURCE=false
 
-
-RUN git config --global user.name "LLVM MinGW" && \
-    git config --global user.email root@localhost
+ENV TOOLCHAIN_PREFIX=/opt/llvm-mingw
+ENV LINUX_LLVM_PREFIX=/opt/ollvm-linux
+ENV RUSTUP_HOME=/opt/rustup
+ENV CARGO_HOME=/opt/cargo
 
 WORKDIR /build
 
-ENV TOOLCHAIN_PREFIX=/opt/llvm-mingw
-
 ARG TOOLCHAIN_ARCHS="i686 x86_64 armv7 aarch64"
-
 ARG DEFAULT_CRT=ucrt
-
 ARG CFGUARD_ARGS=--enable-cfguard
 
-# Build everything that uses the llvm monorepo. We need to build the mingw runtime before the compiler-rt/libunwind/libcxxabi/libcxx runtimes.
-COPY build-llvm.sh build-lldb-mi.sh strip-llvm.sh install-wrappers.sh build-mingw-w64.sh build-mingw-w64-tools.sh build-compiler-rt.sh build-libcxx.sh build-mingw-w64-libraries.sh build-openmp.sh ./
+# Ship patched scripts regardless so reuse builds can pick up updates.
+COPY obfuscator.patch build-host-ollvm.sh build-llvm.sh build-lldb-mi.sh strip-llvm.sh install-wrappers.sh \
+     build-mingw-w64.sh build-mingw-w64-tools.sh build-compiler-rt.sh build-libcxx.sh build-mingw-w64-libraries.sh build-openmp.sh ./
 COPY wrappers/*.sh wrappers/*.c wrappers/*.h ./wrappers/
-RUN ./build-llvm.sh $TOOLCHAIN_PREFIX && \
-    ./build-lldb-mi.sh $TOOLCHAIN_PREFIX && \
-    ./strip-llvm.sh $TOOLCHAIN_PREFIX && \
-    ./install-wrappers.sh $TOOLCHAIN_PREFIX && \
-    ./build-mingw-w64.sh $TOOLCHAIN_PREFIX --with-default-msvcrt=$DEFAULT_CRT $CFGUARD_ARGS && \
-    ./build-mingw-w64-tools.sh $TOOLCHAIN_PREFIX && \
-    ./build-compiler-rt.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
-    ./build-libcxx.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
-    ./build-mingw-w64-libraries.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
-    ./build-compiler-rt.sh $TOOLCHAIN_PREFIX --build-sanitizers && \
-    ./build-openmp.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
-    rm -rf /build/*
 
-ENV PATH=$TOOLCHAIN_PREFIX/bin:$PATH
+RUN install -m 755 build-host-ollvm.sh /usr/local/bin/build-host-ollvm.sh && \
+    install -m 644 obfuscator.patch /usr/local/share/obfuscator.patch && \
+    if [ "${REBUILD_FROM_SOURCE}" = "true" ]; then \
+      apt-get update -qq && \
+      DEBIAN_FRONTEND="noninteractive" apt-get install -qqy --no-install-recommends \
+        git wget bzip2 file unzip libtool pkg-config cmake build-essential \
+        automake yasm gettext autopoint vim-tiny python3 python3-distutils \
+        ninja-build ca-certificates curl less zip musl-dev musl-tools \
+        zlib1g-dev libxml2-dev libedit-dev libncurses-dev libffi-dev libssl-dev \
+        rsync xz-utils patchelf gcc-mingw-w64 g++-mingw-w64 binutils-mingw-w64 \
+        mingw-w64 gcc-mingw-w64-x86-64 gcc-mingw-w64-i686 \
+        binutils-mingw-w64-x86-64 binutils-mingw-w64-i686 mingw-w64-common patch && \
+      apt-get clean -y && \
+      rm -rf /var/lib/apt/lists/* && \
+      git config --global user.name "LLVM MinGW" && \
+      git config --global user.email root@localhost && \
+      ./build-llvm.sh $TOOLCHAIN_PREFIX && \
+      ./build-lldb-mi.sh $TOOLCHAIN_PREFIX && \
+      ./strip-llvm.sh $TOOLCHAIN_PREFIX && \
+      ./install-wrappers.sh $TOOLCHAIN_PREFIX && \
+      ./build-mingw-w64.sh $TOOLCHAIN_PREFIX --with-default-msvcrt=$DEFAULT_CRT $CFGUARD_ARGS && \
+      ./build-mingw-w64-tools.sh $TOOLCHAIN_PREFIX && \
+      ./build-compiler-rt.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
+      ./build-libcxx.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
+      ./build-mingw-w64-libraries.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
+      ./build-compiler-rt.sh $TOOLCHAIN_PREFIX --build-sanitizers && \
+      ./build-openmp.sh $TOOLCHAIN_PREFIX $CFGUARD_ARGS && \
+      rm -rf /build/* && \
+      PATCH_FILE=/usr/local/share/obfuscator.patch /usr/local/bin/build-host-ollvm.sh $LINUX_LLVM_PREFIX && \
+      curl https://sh.rustup.rs -sSf | sh -s -- -y --profile minimal && \
+      $CARGO_HOME/bin/rustup target add x86_64-unknown-linux-gnu x86_64-unknown-linux-musl x86_64-pc-windows-gnu && \
+      ln -sf $CARGO_HOME/bin/* /usr/local/bin/; \
+    else \
+      echo "Reusing toolchains from ${BASE_IMAGE}; skip source rebuild."; \
+    fi
+
+ENV PATH=$LINUX_LLVM_PREFIX/bin:$TOOLCHAIN_PREFIX/bin:$CARGO_HOME/bin:$PATH
